feat: 权限交接 #398
TencentBlueKing/bk-iam-saas pull request #468
Opened 2021-12-02 14:23 UTC by Canway-shiisa

2021-12-03 07:03 UTC, zhu327 commented
修一下lint问题, 建议在本地配一下pre-commit, 避免提交上来的代码ci检查失败

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/account/views.py
> +from ..service.constants import RoleType
避免向上相对引用, 相对引用只引用单前目录下的文件

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/account/views.py
> +        data = self.role_biz.list_user_role("admin")
基于什么考虑改成了admin?

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/account/views.py
> +        data = self.role_biz.list_user_role_members("chace", role_type=role_type)
chace?

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/constants.py
> +        ((Running, _("正在交接")), (Succeed, _("交接成功")), (Failed, _("交接失败")), (PartialFailed, _("部分成功"))))
PartialFailed -> 部分成功 ? 语义不符

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/models.py
> +    object_id = models.CharField("权限ID", max_length=68)  # 用户组ID/系统ID/角色ID
权限ID -> 交接对象ID

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/models.py
> +        # return f"{self.id}-{self.object_type}-{self.object_id}"
去除不必要的注释

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/tasks.py
> +    "system_manager": SystemManHandler,
class的命名写全, 并且保持一致, 如果都有Handler

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/test.py
> +#                 "name": "配置平台",
非比较文件不要提交

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/urls.py
> +    path("records/<int:id>/logs/", views.HandOverRecordsViewSet.as_view({"get": "retrieve"}), name="handover_records_logs")
如果是detail的话, url 后面不应该有 logs, 如果不是detail的话, 就不能用viewSet的retrieve方法

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/utils.py
> +        raise Exception('有正在交接的任务执行...')
定义一个固定的Exception

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/utils.py
> +    task_exist = HandOverRecord.objects.select_for_update().filter(
select_for_update对于mysql值对filter指定为主键的条件有效, 具体可以看下Django文档

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/views.py
> +    @staticmethod
为什么要静态方法?

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/apps/handover/views.py
> +        handover_record = HandOverRecord.objects.create(
get方法中有create?

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/biz/handover.py
> +    subject_groups = GroupBiz().list_subject_group(subject=subject)
考虑下sql直接查询, 而不是全部查出来遍历检查

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/biz/handover.py
> +    subject_polices = PolicyQueryBiz().list_by_subject(system_id=system_id, subject=subject)
同上

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/biz/handover.py
> +    def handler(self):
handler可以定义一个 ABC

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/biz/handover.py
> +    def verify_permission(self):
校验的逻辑需要考虑一下不应该在handler中, 应该有一个单独校验类或者方法, 统一的抽象定义

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/biz/handover.py
> +    def verify_permission(self):
校验就是校验, handler就是handler, 职责单一

2021-12-03 07:29 UTC, zhu327 commented on saas/backend/service/role.py
> +    def list_user_role_members(self, user_id: str, role_type: List[RoleType]) -> List[UserRole]:
user_role_with_members?

2021-12-03 09:11 UTC, nannan00 requested changes

2021-12-03 09:11 UTC, nannan00 commented on saas/backend/biz/handover.py
> +            self.grant_and_remove()
handler 层应该体现出 grant 和 revoke 逻辑，而不是合并在一起，然后实现的类去处理

这里应该是统一处理了 handler的一些功能逻辑，比如 grant失败了，如何处理，是否继续执行revoke？是否记录日志？日志是否记录具体是grant失败还是revoke失败等等

2021-12-03 09:11 UTC, nannan00 commented on saas/backend/biz/handover.py
> +    def handler(self):
handler里是否应包括调用处理 任务提交的详细数据，用于后续交接，不应该是在init函数里处理非公共逻辑

每个子类需要实现其各种的处理任务提交的详细数据

2021-12-03 09:11 UTC, nannan00 commented on saas/backend/biz/handover.py
> +        verify_flag = verify_group_permission(subject=self.remove_subject, group_id=self.object_id)
verify_flag 命名不合适，  is_pass?

2021-12-03 09:11 UTC, nannan00 commented on saas/backend/service/role.py
> +        return sorted_data
list_user_role_members 逻辑太定制了，完全就是为了一个接口提供的

没有考虑本身 Role和 Member是两个抽象

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/models.py
> +    transferor = models.CharField("被交接人", max_length=64)
executor / transferor 不看注释单纯从命名看不出哪个是交接人/被交接人

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/models.py
> +class HandOverTaskDetail(TimestampedModel):
+1

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/models.py
> +    error_info = models.TextField("交接异常信", default="")
"交接异常信" ? 异常信息?

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/models.py
> +    handover_record_id = models.IntegerField("交接任务id")
这里没有外键关联?

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/serializers.py
> +    transferor = serializers.CharField(label="目标交接人")
上面是`被交接人`, 这里是`目标交接人`, 需要尽量保持一致

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/tasks.py
> +    "rating_manager": RatingManHandler
rating_manager 分级管理员不能在用`rating`了, 用`grade`!

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/tasks.py
> +    return status
不要用`status`状态量, 分支中直接`return`

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/urls.py
> +    path("records/<int:id>/logs/", views.HandOverRecordsViewSet.as_view({"get": "retrieve"}), name="handover_records_logs")
日志只是任务的一个字段

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/utils.py
> +        raise Exception('有正在交接的任务执行...')
使用固定的错误码

2021-12-06 06:31 UTC, wklken commented on saas/backend/apps/handover/views.py
> +        handover_record = HandOverRecord.objects.create(
+1, 放错地方了? get 应该只有查询

2021-12-06 06:31 UTC, wklken commented on saas/backend/biz/handover.py
> +    def grant_and_remove(self):
grant / revoke?

2021-12-06 06:31 UTC, wklken commented on saas/backend/biz/handover.py
> +class RatingManHandler(BaseHandover):
Rating to Grade

2021-12-07 11:34 UTC, nannan00 requested changes

2021-12-07 11:34 UTC, nannan00 commented on saas/backend/apps/handover/constants.py
> +            ),
风格需要保持一致

2021-12-07 11:34 UTC, nannan00 commented on saas/backend/apps/handover/constants.py
> +    CUSTOM = auto()
CUSTOM => CUSTOM_PERM

2021-12-10 09:03 UTC, closed without merging